// chapter_08/d3-with-svelte/src/ChartComponents/Label.svelte
<script>
  export let x;
  export let y;
  export let color;
  export let textAnchor;
  export let label;
</script>

<style>
  text {
    font-weight: bold;
    transition: transform 400ms cubic-bezier(0.33, 1, 0.68, 1);
  }
</style>

<text
  x={0}
  y={0}
  fill={color}
  text-anchor={textAnchor}
  alignment-baseline="middle"
  style="transform: {`translate(${x}px, ${y}px)`};"
>
  {label}
</text>

// chapter_08/d3-with-angular/src/app/chart-components/label/label.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: '[appLabel]',
  templateUrl: './label.component.html',
  styleUrls: ['./label.component.css']
})
export class LabelComponent {
  @Input() x: number = 0;
  @Input() y: number = 0;
  @Input() fill: string = '#000';
  @Input() label: string = '';
  @Input() textAnchor: string = 'start';

  getTransform() {
    return `translate(${this.x}px, ${this.y}px)`;
  }
}

<svg:text
  [attr.x]="0"
  [attr.y]="0"
  [attr.fill]="fill"
  [attr.text-anchor]="textAnchor"
  [attr.alignment-baseline]="'middle'"
  [style.transform]="getTransform()"
>
  {{label}}
</svg:text>
