// chapter_08/d3-with-svelte/src/UI/Badge.svelte
<script>
  import Circle from "../ChartComponents/Circle.svelte";

  export let translation;
  export let strokeColor;
  export let label;
</script>

<style>
  text {
    font-size: 12px;
    font-weight: bold;
  }
</style>

<g transform={`translate(${translation[0]}, ${translation[1]})`}>
  <Circle 
    cx={0}
    cy={0}
    r={18}
    fill={"#fff"}
    stroke={strokeColor}
    strokeWidth={3}
  />
  <text
    text-anchor="middle"
    alignment-baseline="middle"
    fill="#374f5e"
  >
    {label}
  </text>
</g>

// chapter_08/d3-with-angular/src/app/ui/badge/badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: '[appBadge]',
  templateUrl: './badge.component.html',
  styleUrls: ['./badge.component.css']
})
export class BadgeComponent {
  @Input() translation: Array<number> = [];
  @Input() strokeColor: string = '#000';
  @Input() label: string = '';

  getTranslation() {
    return `translate(${this.translation[0]}px, ${this.translation[1]}px)`;
  }
}

<svg:g [style.transform]="getTranslation()">
  <svg:circle 
    [attr.cx]="0"
    [attr.cy]="0"
    [attr.r]="18"
    [attr.fill]="'#fff'"
    [attr.stroke]="strokeColor"
    [attr.stroke-width]="3"
  ></svg:circle>
  <svg:text
    [attr.text-anchor]="'middle'"
    [attr.alignment-baseline]="'middle'"
    [attr.fill]="'#374f5e'"
    style="font-size: 12px; font-weight: bold;"
  >
    {{label}}
  </svg:text>
</svg:g>
