// chapter_08/d3-with-angular/src/app/charts/bar-chart/bar-chart.component.ts
import { Component, Input } from '@angular/core';
import * as d3 from 'd3';

import { MarginType } from 'src/app/utils/types';

@Component({
  selector: 'app-bar-chart',
  templateUrl: './bar-chart.component.html',
  styleUrls: ['./bar-chart.component.css']
})
export class BarChartComponent {
  @Input() data: any;
  @Input() margin!: MarginType;
  @Input() colorScale: any;

  width = 300;
  height = 245;
  marginBottom = 85;
  innerWidth = 0;
  innerHeight = 0;

  awarenessData: Array<any> = [];
  ticksArray: Array<string> = [];
  xScale = d3.scaleBand();
  yScale = d3.scaleLinear();

  ngOnInit() {
    this.initializeScales();
  }

  initializeScales() {
    this.innerWidth = this.width - this.margin.left - this.margin.right;
    this.innerHeight = this.height - this.margin.top - this.marginBottom;

    this.data.forEach((d: { id: string; name: string; awareness: any; }) => {
      const awareness: { id: string; name: string; awareness_percentage: number; } = { 
        id: d.id, 
        name: d.name,
        awareness_percentage: d.awareness[d.awareness.length -1].percentage_question 
      };
      this.awarenessData.push(awareness);
    });
    this.awarenessData.sort((a: { awareness_percentage: number; }, b: { awareness_percentage: number; }) => b.awareness_percentage - a.awareness_percentage);
    this.ticksArray = this.awarenessData.map(d => d.name);

    const maxUsers:any = d3.max(this.data, (d:any) => d.user_count);
    this.xScale
      .domain(this.awarenessData.map((d: { name: any; }) => d.name))
      .range([0, this.innerWidth])
      .padding(0.2);
    this.yScale
      .domain([0, 100])
      .range([this.innerHeight, 0]);
  }

  trackByFn(index: number, d: any) {
    return `bar-${d.id}`;
  }
}

<app-card>
  <h2>Retention vs Usage</h2>
  <app-chart-container
    [width]="width"
    [height]="height"
    [margin]="margin"
  >
    <svg:g appAxis
      [type]="'band'"
      [scale]="xScale"
      [ticksArray]="ticksArray"
      [innerWidth]="innerWidth"
      [innerHeight]="innerHeight"
    ></svg:g>
    <svg:g appAxis
      [type]="'left'"
      [scale]="yScale"
      [innerWidth]="innerWidth"
      [innerHeight]="innerHeight"
      label="{{'Awareness %'}}"
    ></svg:g>
    <svg:rect *ngFor="let d of awarenessData, index as i; trackBy: trackByFn"
      [attr.x]="xScale(d.name)"
      [attr.y]="yScale(d.awareness_percentage)"
      [attr.width]="xScale.bandwidth()"
      [attr.height]="innerHeight - yScale(d.awareness_percentage)"
      [attr.fill]="colorScale(d.id)"
    />
  </app-chart-container>
</app-card>

// chapter_08/d3-with-svelte/src/Charts/BarChart.svelte
<script>
  import * as d3 from "d3";

  import Card from "../UI/Card.svelte";
  import ChartContainer from "../ChartComponents/ChartContainer.svelte";
  import Axis from "../ChartComponents/Axis.svelte";
  import Rectangle from "../ChartComponents/Rectangle.svelte";
    import { color } from "d3";

  export let margin;
  export let data;
  export let colorScale;

  const width = 300;
  const height = 245;
  const marginBottom = 85;
  const innerWidth = width - margin.left - margin.right;
  const innerHeight = height - margin.top - marginBottom;

  const awarenessData = [];
  data.forEach(d => {
    const awareness = { 
      id: d.id, 
      name: d.name,
      awareness_percentage: d.awareness[d.awareness.length -1].percentage_question 
    };
    awarenessData.push(awareness);
  });
  awarenessData.sort((a, b) => b.awareness_percentage - a.awareness_percentage);

  const xScale = d3.scaleBand()
    .domain(awarenessData.map(d => d.name))
    .range([0, innerWidth])
    .padding(0.2);
  const yScale = d3.scaleLinear()
    .domain([0, 100])
    .range([innerHeight, 0]);
</script>

<Card>
  <h2>Awareness</h2>
  <ChartContainer
    width={width}
    height={height}
    margin={margin}
  >
    {#if data && colorScale}
      <Axis 
        type="band"
        scale={xScale}
        ticksArray={awarenessData.map(d => d.name)}
        innerWidth={innerWidth}
        innerHeight={innerHeight}
      />
      <Axis 
        type="left"
        scale={yScale}
        innerWidth={innerWidth}
        innerHeight={innerHeight}
        label={"Awareness %"}
      />
      {#each awarenessData as framework (framework.id)}
        <Rectangle
          x={xScale(framework.name)}
          y={yScale(framework.awareness_percentage)}
          width={xScale.bandwidth()}
          height={innerHeight - yScale(framework.awareness_percentage)}
          fill={colorScale(framework.id)}
        />
      {/each}
    {/if}
  </ChartContainer>
</Card>
