// chapter_08/d3-with-angular/src/app/charts/rankings/rankings.component.ts
import { Component, Input, OnInit } from '@angular/core';
import * as d3 from 'd3';

import { MarginType } from 'src/app/utils/types';

@Component({
  selector: 'app-rankings',
  templateUrl: './rankings.component.html',
  styleUrls: ['./rankings.component.css']
})
export class RankingsComponent {
  @Input() data: any;
  @Input() margin!: MarginType;
  @Input() colorScale: any;

  width = 1000;
  height = 542;
  marginRight = 150;
  marginLeft = 110;
  innerWidth = 0;
  innerHeight = 0;

  xScale = d3.scalePoint();
  yScale = d3.scalePoint();
  xAccessor: any = (d: {year: number, rank: number, percentage_question: number}) => {
    return this.xScale(d.year.toString());
  }
  yAccessor: any = (d: {year: number, rank: number, percentage_question: number}) => {
    if (d.rank) {
      return this.yScale(d.rank.toString());
    }
    return null;
  }

  rankingFilters = [
    { id: "satisfaction", label: "Satisfaction" },
    { id: "interest", label: "Interest" },
    { id: "usage", label: "Usage" },
    { id: "awareness", label: "Awareness" },
  ];
  activeFilter = "satisfaction";

  ngOnInit() {
    this.initializeVariables();
  }

  initializeVariables() {
    this.innerWidth = this.width - this.marginLeft - this.marginRight;
    this.innerHeight = this.height - this.margin.top - this.margin.bottom;

    const years = this.data.years.map((year: number) => year.toString());
    this.xScale
      .domain(years)
      .range([0, this.innerWidth]);
    const ranks: any = d3.range(1, this.data.ids.length + 1).map((rank: number) => rank.toString());
    this.yScale
      .domain(ranks)
      .range([0, this.innerHeight]);
  }

  labelVerticalPosition(item: Array<any>, position: string) {
    if (position === "left" && item[0].rank) {
      return this.yScale(item[0].rank.toString());
    } else if (position === "right") {
      return this.yScale(item[item.length - 1].rank.toString());
    } else {
      return 0;
    }
  }

  translateTick(year: number) {
    return `translate(${this.xScale(year.toString())}, 0)`;
  }

  getBadgeTranslation(selection: {year: number, rank: number, percentage_question: number }) {
    return [
      parseFloat(this.xScale(selection.year.toString()) as unknown as string), 
      parseFloat(this.yScale(selection.rank.toString()) as unknown as string)
    ];
  }

  getPercentageLabel(percentage: number) {
    return `${Math.round(percentage)}%`;
  }

  handleClick(id: string) {
    this.activeFilter = id;
  }
}

<app-card>
  <h2>Rankings</h2>
  <app-ranking-filters 
    [filters]="rankingFilters"
    [activeFilter]="activeFilter"
    (clickDetected)="handleClick($event)"
  ></app-ranking-filters>
  <app-chart-container
    [width]="width"
    [height]="height"
    [margin]="{top: margin.top, right: marginRight, bottom: margin.bottom, left: marginLeft}"
  >
    <svg:g 
      *ngFor="let year of data.years" 
      class="axis" 
      [attr.transform]="translateTick(year)"
    >
      <svg:line 
        [attr.x1]="0"
        [attr.y1]="innerHeight"
        [attr.x2]="0"
        [attr.y2]="0"
        [attr.stroke-dasharray]="'6 4'"
      />
      <svg:text
        [attr.x]="0"
        [attr.y]="innerHeight + 40"
        [attr.text-anchor]="'middle'"
      >
        {{year}}
      </svg:text>
    </svg:g>
    <svg:g *ngFor="let framework of data.experience">
      <svg:g appCurve
        [data]="framework[activeFilter]"
        [stroke]="colorScale(framework.id)" 
        [strokeWidth]="5"
        [xAccessor]="xAccessor"
        [yAccessor]="yAccessor"
      ></svg:g>
      <svg:g appLabel
        *ngIf="framework[activeFilter][0].rank !== null"
        [x]="-25"
        [y]="labelVerticalPosition(framework[activeFilter], 'left')!"
        [fill]="colorScale(framework.id)"
        [label]="framework.name"
        [textAnchor]="'end'"
      ></svg:g>
      <svg:g appLabel
        [x]="innerWidth + 25"
        [y]="labelVerticalPosition(framework[activeFilter], 'right')!"
        [fill]="colorScale(framework.id)"
        [label]="framework.name"
      ></svg:g>
      <svg:g *ngFor="let selection of framework[activeFilter]">
        <svg:g appBadge
          *ngIf="selection.rank !== null"
          [translation]="getBadgeTranslation(selection)"
          [strokeColor]="colorScale(framework.id)"
          [label]="getPercentageLabel(selection.percentage_question)"
        ></svg:g>
      </svg:g>
    </svg:g>
  </app-chart-container>
</app-card>

// chapter_08/d3-with-svelte/src/Charts/Rankings.svelte
<script>
  import * as d3 from "d3";

  import Card from "../UI/Card.svelte";
  import ChartContainer from "../ChartComponents/ChartContainer.svelte";
  import RankingFilters from "../Interactions/RankingFilters.svelte";
  import Curve from "../ChartComponents/Curve.svelte";
  import Label from "../ChartComponents/Label.svelte";
  import Badge from "../UI/Badge.svelte";

  export let margin;
  export let data;
  export let colorScale;

  const width = 1000;
  const height = 542;
  const marginRight = 150;
  const marginLeft = 110;
  const innerWidth = width - marginLeft - marginRight;
  const innerHeight = height - margin.top - margin.bottom;

  const rankingFilters = [
    { id: "satisfaction", label: "Satisfaction" },
    { id: "interest", label: "Interest" },
    { id: "usage", label: "Usage" },
    { id: "awareness", label: "Awareness" },
  ];
  let activeFilter = "satisfaction";

  const xScale = d3.scalePoint()
    .domain(data.years)
    .range([0, innerWidth]);
  const ranks = d3.range(1, data.ids.length + 1);
  const yScale = d3.scalePoint()
    .domain(ranks)
    .range([0, innerHeight]);
</script>

<Card>
  <h2>Rankings</h2>
  <RankingFilters
    filters={rankingFilters}
    activeFilter={activeFilter}
  />
  <ChartContainer
    width={width}
    height={height}
    margin={{top: margin.top, right: marginRight, bottom: margin.bottom, left: marginLeft}}
  >
  {#if data && colorScale}
    {#each data.years as year (`line-year-${year}`)}
      <g class="axis" transform={`translate(${xScale(year)}, 0)`}>
        <line 
          x1={0}
          y1={innerHeight}
          x2={0}
          y2={0}
          stroke-dasharray={"6 4"}
        />
        <text
          x={0}
          y={innerHeight + 40}
          text-anchor="middle"
        >
          {year}
        </text>
      </g>
    {/each}
    {#each data.experience as framework (`curve-${framework.id}`)}
      <g>
        <Curve
          data={framework[activeFilter]}
          xScale={xScale}
          yScale={yScale}
          xAccessor="year"
          yAccessor="rank"
          stroke={colorScale(framework.id)}
          strokeWidth={5}
        />
        {#if framework[activeFilter][0].rank}
          <Label
            x={-25}
            y={yScale(framework[activeFilter][0].rank)}
            color={colorScale(framework.id)}
            label={framework.name}
            textAnchor={"end"}
          />
        {/if}
        <Label
          x={innerWidth + 25}
          y={yScale(framework[activeFilter][framework[activeFilter].length - 1].rank)}
          color={colorScale(framework.id)}
          label={framework.name}
          textAnchor={"start"}
        />
        {#each framework[activeFilter] as selection, i (`${framework.id}-selection-${i}`)}
          {#if selection.rank}
             <Badge
              translation={[xScale(selection.year), yScale(selection.rank)]}
              strokeColor={colorScale(framework.id)}
              label={`${Math.round(selection.percentage_question)}%`}
            />
          {/if}
        {/each}
      </g>
    {/each}
    {/if}
  </ChartContainer>
</Card>
