// chapter_08/d3-with-svelte/src/ChartComponents/Curve.svelte
<script>
  import { onMount } from "svelte";
  import * as d3 from "d3";

  export let data;
  export let xScale;
  export let yScale;
  export let xAccessor;
  export let yAccessor;
  export let stroke;
  export let strokeWidth;

  let pathRef;

  const lineGenerator = d3.line()
    .x(d => xScale(d[xAccessor]))
    .y(d => yScale(d[yAccessor]))
    .defined(d => d[yAccessor] !== null)
    .curve(d3.curveMonotoneX);

  onMount(() => {
    updatePath(data);
  })

  $: updatePath(data);

  const updatePath = (d) => {
    console.log("update", d)
    d3.select(pathRef)
      .transition()
      .duration(400)
      .ease(d3.easeCubicOut)
        .attr("d", lineGenerator(d));
  }
</script>

<path
bind:this={pathRef}
  fill="none" 
  stroke={stroke} 
  stroke-width={strokeWidth}
/>

// chapter_08/d3-with-angular/src/app/chart-components/curve/curve.component.ts
import { Component, Input, OnInit, ElementRef, ViewChild, OnChanges } from '@angular/core';
import * as d3 from 'd3';

@Component({
  selector: '[appCurve]',
  templateUrl: './curve.component.html',
  styleUrls: ['./curve.component.css']
})
export class CurveComponent {
  @Input() data: Array<any> = [];
  @Input() stroke: string = "#000";
  @Input() strokeWidth: number = 1;
  @Input() xAccessor: any;
  @Input() yAccessor: any;
  @ViewChild('path') pathRef!: ElementRef<SVGElement>;

  lineGenerator = d3.line();

  ngOnInit() {
    this.initializeVariables();
  }

  ngAfterViewInit(): void {
    this.updatePath();
  }

  ngOnChanges() {
    if (this.pathRef) {
      this.updatePath();
    }
  }

  initializeVariables() {
    this.lineGenerator
      .x(d => this.xAccessor(d))
      .y(d => this.yAccessor(d))
      .defined(d => this.yAccessor(d) !== null)
      .curve(d3.curveMonotoneX);
  }

  updatePath() {
    d3.select(this.pathRef.nativeElement)
      .transition()
      .duration(400)
      .ease(d3.easeCubicOut)
        .attr("d", this.lineGenerator(this.data));
  }
}

<svg:path
  #path
  [attr.fill]="'none'" 
  [attr.stroke]="stroke" 
  [attr.stroke-width]="strokeWidth"
/>
