// chapter_08/d3-with-svelte/src/ChartComponents/Axis.svelte
<script>
  import * as d3 from "d3";

  export let type;
  export let scale;
  export let innerWidth;
  export let innerHeight;
  export let label = "";
  export let ticksArray = [];

  let divider;

  if (type === "bottom") {
    divider = 100;
  } else if (type === "left") {
    divider = 50;
  }
  const numberOfTicks = innerWidth / divider;
  let ticks;
  if (type !== "band") {
    ticks = scale.ticks(numberOfTicks);
  }
</script>

{#if type === "bottom"}
  <g class="axis" transform={`translate(0, ${innerHeight})`} > 
    <line x1={0} y1={0} x2={innerWidth} y2={0} />
    {#each ticks as tick, i (`tick-bottom-${tick}`)}
      <g transform={`translate(${scale(tick)}, 0)`}>
        <line x1={0} y1={0} x2={0} y2={5} />
        <text x={0} y={20} text-anchor="middle">
          {tick}
        </text>
      </g>
    {/each}
    {#if label !== ""}
      <text
        text-anchor="middle"
        transform={`translate(${innerWidth / 2}, 45)`}
      >
        {label}
      </text>
    {/if}
  </g>
{:else if type === "left"}
  <g class="axis">
    <line x1={0} y1={innerHeight} x2={0} y2={0} />
    {#each ticks as tick, i (`tick-left-${tick}`)}
      <g transform={`translate(0, ${scale(tick)})`}>
        <line x1={-5} y1={0} x2={0} y2={0} />
        <text x={-10} y={0} text-anchor="end" alignment-baseline="middle">
          {tick}
        </text>
      </g>
    {/each}
    {#if label !== ""}
      <text
        text-anchor="middle"
        transform={`translate(-42, ${innerHeight / 2}) rotate(-90)`}
      >
        {label}
      </text>
    {/if}
  </g>
{:else if type === "band"}
  <g class="axis" transform={`translate(0, ${innerHeight})`} >
    <line x1={0} y1={0} x2={innerWidth} y2={0} />
    {#each ticksArray as tick (`tick-band-${tick}`)}
      <text
        text-anchor="end"
        alignment-baseline="middle"
        transform={`translate(${scale(tick) + scale.bandwidth() / 2}, 8) rotate(-90)`}
      >
        {tick}
      </text>
    {/each}
  </g>
{/if}

// chapter_08/d3-with-angular/src/app/chart-components/axis/axis.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: '[appAxis]',
  templateUrl: './axis.component.html',
  styleUrls: ['./axis.component.css']
})
export class AxisComponent {
  @Input() type: string = '';
  @Input() scale: any;
  @Input() innerWidth: number = 0;
  @Input() innerHeight: number = 0;
  @Input() label?: string;
  @Input() ticksArray?: Array<any> = [];

  axisTranslation = '';
  labelTransform = '';
  numberOfTicks = 0;
  ticks = [];

  ngOnInit() {
    this.setTranslations();
    this.calculateNumberOfTicks();
  }

  setTranslations() {
    if (this.type === 'bottom' || this.type === "band") {
      this.axisTranslation = `translate(0, ${this.innerHeight})`;
      if (this.label) {
        this.labelTransform = `translate(${this.innerWidth / 2}, 45)`;
      }
    } else if (this.type === 'left' && this.label) {
      this.labelTransform = `translate(-42, ${this.innerHeight / 2}) rotate(-90)`;
    }
  }

  calculateNumberOfTicks() {
    if (this.type === 'bottom') {
      this.numberOfTicks = this.innerWidth / 100;
    } else if (this.type === 'left') {
      this.numberOfTicks = this.innerHeight / 50;
    }
    if (this.type !== "band") {
      this.ticks = this.scale.ticks(this.numberOfTicks);
    }
  }

  transformBandLabel(tick: string) {
    return `translate(${this.scale(tick) + this.scale.bandwidth() / 2}, 8) rotate(-90)`;
  }

  trackByFn(index:number) {
    return `tick-${this.type}-${index}`;
  }

}

<svg:g 
  *ngIf="type === 'bottom'"
  class="axis"
  [attr.transform]="axisTranslation"
>
  <svg:line
    [attr.x1]="0" 
    [attr.y1]="0"
    [attr.x2]="innerWidth" 
    [attr.y2]="0"
  />
  <svg:g *ngFor="let tick of ticks; index as i; trackBy: trackByFn" >
    <svg:line
      [attr.x1]="scale(tick)" 
      [attr.y1]="0"
      [attr.x2]="scale(tick)" 
      [attr.y2]="5"
    />
    <svg:text
      [attr.x]="scale(tick)"
      [attr.y]="20"
      [attr.text-anchor]="'middle'"
    >
      {{tick}}
    </svg:text>
  </svg:g>
  <text
    *ngIf="label"
    class="axis-label"
    [attr.text-anchor]="'middle'"
    [attr.transform]="labelTransform"
  >
    {{label}}
  </text>
</svg:g>

<svg:g 
  *ngIf="type === 'left'"
  class="axis"
>
  <svg:line
    [attr.x1]="0" 
    [attr.y1]="innerHeight"
    [attr.x2]="0" 
    [attr.y2]="0"
  />
  <svg:g *ngFor="let tick of ticks; index as i; trackBy: trackByFn" >
    <svg:line
      [attr.x1]="-5" 
      [attr.y1]="scale(tick)"
      [attr.x2]="0" 
      [attr.y2]="scale(tick)"
    />
    <svg:text
      [attr.x]="-10"
      [attr.y]="scale(tick)"
      [attr.text-anchor]="'end'"
      [attr.alignment-baseline]="'middle'"
    >
      {{tick}}
    </svg:text>
  </svg:g>
  <text
    *ngIf="label"
    [attr.text-anchor]="'middle'"
    [attr.transform]="labelTransform"
  >
    {{label}}
  </text>
</svg:g>

<svg:g 
  *ngIf="type === 'band'"
  class="axis"
  [attr.transform]="axisTranslation"
>
  <svg:line
    [attr.x1]="0" 
    [attr.y1]="0"
    [attr.x2]="innerWidth" 
    [attr.y2]="0"
  />
  <svg:text *ngFor="let tick of ticksArray; index as i; trackBy: trackByFn"
    [attr.text-anchor]="'end'"
    [attr.alignment-baseline]="'middle'"
    [attr.transform]="transformBandLabel(tick)"
  >
    {{tick}}
  </svg:text>
</svg:g>
